### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by liutaihua** [iron/session#27]
src/sessionstore/session.rs:42:45: 42:46 error: expected type, found `|`
src/sessionstore/session.rs:42     pub fn upsert(&self, value: V, mutator: |&mut V|) -> V {

cargo --version
cargo 0.7.0-nightly (7c3b8ef 2015-11-30)

rustc --version
rustc 1.6.0-nightly (a2866e387 2015-11-30)

**Comment by russoue** [comment]
I am having a different problem:

    > cargo --version
    cargo 0.7.0-nightly (488e8d8 2015-12-04)
    > rustc --version
    rustc 1.4.0 (8ab8581f6 2015-10-27)
    > cargo build
    failed to parse manifest at `/path/to/session/Cargo.toml`
    
    Caused by:
      expected a value of type `table`, but found a value of type `array` for the key `lib`

**Comment by BruceL33t** [comment]
There's a lot of other problems as well: https://github.com/iron/session/pull/23#issuecomment-149341498

**Comment by Hoverbear** [comment]
This is fixed.
